---
# tasks file for infra.apache
- name: Instala apache y firewalld
  yum:
    name:
      - httpd
      - firewalld
    state: latest

- name: Archivo de configuración para Apache
  template:

  notify:
    - reinicia apache

- name: Archivo de configuración del firewall
  template:

  notify:
    - reinicia firewall
