---
# tasks file for infra.apache
- name: Instala apache y firewalld
  yum:
    name:
      - "{{ web_pkg }}"
      - "{{ fw_pkg }}"
    state: latest

- name: Archivo de configuración del firewall
  template:
    src: firewalld.j2
    dest: /etc/firewalld/zones/public.xml
  notify:
    - reinicia firewall
