---
# tasks file for infra.apache
- name: Instala apache y firewalld
  yum:
    name:
      - httpd
      - firewalld
    state: latest

- name: Archivo de configuración para Apache
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: "Listen {{ item.user_port  }}"
  loop: "{{ web_developers }}"
  notify:
    - reinicia apache

- name: Archivo de configuración del firewall
  template:
    src: firewalld.j2
    dest: /etc/firewalld/zones/public.xml
  notify:
    - reinicia firewall
